### ISSUE TITLE
Pasting over groups no longer works in Sketch 62

### ISSUE THREAD

**Issue by highvoltaged** [ajilderda/Sketch-Copy-Paste-Position-Size#6]
Pasting over groups no longer works in Sketch 62

It works on single layers,but not on groups.

**Comment by ajilderda** [comment]
Hi @highvoltaged, I'm not entirely sure what you mean by pasting over groups. But since it was still relying on some old sketchy (🤦) API's it could be some actions broke. I've just pushed an update. Can you please check and report back if this fixes your issue?:
https://github.com/ajilderda/Sketch-Copy-Paste-Position-Size/releases

**Comment by highvoltaged** [comment]
Hi, sorry, i switched to Figma a year ago.
But as far as i remember "Pasting over groups" meant executing the resize command while grouped objects were selected.

**Comment by ajilderda** [comment]
No worries! Thanks for the update.
